[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "kookablockly"
authors = [{name = "Julian Dinsdale", email = "jwdinsdale@outlook.com"}]
dynamic = ["version", "description"]
